version: "3"
services:
    api:
        build: ./src/MadraCare.Services/MadraCare.Services.Api
        ports:
            - "8001:80"
    web:
        build: ./src/MadraCare.Website
        ports:
            - "8000:80"
        depends_on:
            - api
