version: "3"
services:
    services.kennel:
        build: ./src/MadraCare.Services/MadraCare.Services.Kennel
    services.gateway:
        build: ./src/MadraCare.Services/MadraCare.Services.Gateway
        depends_on:
            - services.kennel
    web:
        build: ./src/MadraCare.Website
        ports:
            - "8000:80"
        depends_on:
            - services.gateway
